const db = require("../models");

const settings = [
  // COMPANY
  {
    channel: "GLOBAL",
    group: "company",
    key: "displayName",
    label: "Company Display Name",
    value: "MyShops",
    defaultValue: "MyShops",
    dataType: "STRING",
    isPublic: true,
    isRequired: true,
    displayOrder: 10,
  },
  {
    channel: "GLOBAL",
    group: "company",
    key: "legalName",
    label: "Legal Company Name",
    value: "MyShops",
    defaultValue: "MyShops",
    dataType: "STRING",
    isPublic: false,
    displayOrder: 20,
  },
  {
    channel: "GLOBAL",
    group: "company",
    key: "logoUrl",
    label: "Primary Logo",
    value: null,
    defaultValue: null,
    dataType: "IMAGE",
    isPublic: true,
    displayOrder: 30,
  },
  {
    channel: "WEBSITE",
    group: "company",
    key: "faviconUrl",
    label: "Website Favicon",
    value: null,
    defaultValue: null,
    dataType: "IMAGE",
    isPublic: true,
    displayOrder: 40,
  },

  // THEME
  {
    channel: "GLOBAL",
    group: "theme",
    key: "primaryColor",
    label: "Primary Color",
    value: "#111111",
    defaultValue: "#111111",
    dataType: "COLOR",
    isPublic: true,
    isRequired: true,
    displayOrder: 10,
  },
  {
    channel: "GLOBAL",
    group: "theme",
    key: "secondaryColor",
    label: "Secondary Color",
    value: "#F4F4F4",
    defaultValue: "#F4F4F4",
    dataType: "COLOR",
    isPublic: true,
    displayOrder: 20,
  },
  {
    channel: "GLOBAL",
    group: "theme",
    key: "accentColor",
    label: "Accent Color",
    value: "#0066FF",
    defaultValue: "#0066FF",
    dataType: "COLOR",
    isPublic: true,
    displayOrder: 30,
  },
  {
    channel: "GLOBAL",
    group: "theme",
    key: "backgroundColor",
    label: "Page Background Color",
    value: "#FFFFFF",
    defaultValue: "#FFFFFF",
    dataType: "COLOR",
    isPublic: true,
    displayOrder: 40,
  },
  {
    channel: "GLOBAL",
    group: "theme",
    key: "surfaceColor",
    label: "Card Background Color",
    value: "#FFFFFF",
    defaultValue: "#FFFFFF",
    dataType: "COLOR",
    isPublic: true,
    displayOrder: 50,
  },
  {
    channel: "GLOBAL",
    group: "theme",
    key: "textColor",
    label: "Primary Text Color",
    value: "#111111",
    defaultValue: "#111111",
    dataType: "COLOR",
    isPublic: true,
    displayOrder: 60,
  },
  {
    channel: "GLOBAL",
    group: "theme",
    key: "mutedTextColor",
    label: "Muted Text Color",
    value: "#6B7280",
    defaultValue: "#6B7280",
    dataType: "COLOR",
    isPublic: true,
    displayOrder: 70,
  },
  {
    channel: "GLOBAL",
    group: "theme",
    key: "borderColor",
    label: "Border Color",
    value: "#E5E7EB",
    defaultValue: "#E5E7EB",
    dataType: "COLOR",
    isPublic: true,
    displayOrder: 80,
  },
  {
    channel: "GLOBAL",
    group: "theme",
    key: "fontFamily",
    label: "Font Family",
    value: "Inter",
    defaultValue: "Inter",
    dataType: "SELECT",
    options: [
      {
        label: "Inter",
        value: "Inter",
      },
      {
        label: "Manrope",
        value: "Manrope",
      },
      {
        label: "Poppins",
        value: "Poppins",
      },
      {
        label: "Roboto",
        value: "Roboto",
      },
    ],
    isPublic: true,
    displayOrder: 90,
  },
  {
    channel: "GLOBAL",
    group: "theme",
    key: "buttonRadius",
    label: "Button Corner Radius",
    value: 8,
    defaultValue: 8,
    dataType: "NUMBER",
    isPublic: true,
    displayOrder: 100,
  },
  {
    channel: "GLOBAL",
    group: "theme",
    key: "cardRadius",
    label: "Card Corner Radius",
    value: 12,
    defaultValue: 12,
    dataType: "NUMBER",
    isPublic: true,
    displayOrder: 110,
  },

  // WEBSITE
  {
    channel: "WEBSITE",
    group: "website",
    key: "wishlistEnabled",
    label: "Enable Wishlist",
    value: true,
    defaultValue: true,
    dataType: "BOOLEAN",
    isPublic: true,
    displayOrder: 10,
  },
  {
    channel: "WEBSITE",
    group: "website",
    key: "comparisonEnabled",
    label: "Enable Product Comparison",
    value: true,
    defaultValue: true,
    dataType: "BOOLEAN",
    isPublic: true,
    displayOrder: 20,
  },
  {
    channel: "WEBSITE",
    group: "website",
    key: "reviewsEnabled",
    label: "Enable Product Reviews",
    value: true,
    defaultValue: true,
    dataType: "BOOLEAN",
    isPublic: true,
    displayOrder: 30,
  },
  {
    channel: "WEBSITE",
    group: "website",
    key: "recentlyViewedEnabled",
    label: "Enable Recently Viewed",
    value: true,
    defaultValue: true,
    dataType: "BOOLEAN",
    isPublic: true,
    displayOrder: 40,
  },
  {
    channel: "WEBSITE",
    group: "website",
    key: "guestCheckoutEnabled",
    label: "Enable Guest Checkout",
    value: true,
    defaultValue: true,
    dataType: "BOOLEAN",
    isPublic: true,
    displayOrder: 50,
  },
  {
    channel: "WEBSITE",
    group: "website",
    key: "aiAssistantEnabled",
    label: "Enable Website AI Assistant",
    value: true,
    defaultValue: true,
    dataType: "BOOLEAN",
    isPublic: true,
    displayOrder: 60,
  },
  {
    channel: "WEBSITE",
    group: "website",
    key: "showInventory",
    label: "Show Inventory Availability",
    value: true,
    defaultValue: true,
    dataType: "BOOLEAN",
    isPublic: true,
    displayOrder: 70,
  },
  {
    channel: "WEBSITE",
    group: "website",
    key: "showLowStock",
    label: "Show Low Stock Messages",
    value: true,
    defaultValue: true,
    dataType: "BOOLEAN",
    isPublic: true,
    displayOrder: 80,
  },

  // KIOSK
  {
    channel: "KIOSK",
    group: "kiosk",
    key: "aiAssistantEnabled",
    label: "Enable Kiosk AI Assistant",
    value: true,
    defaultValue: true,
    dataType: "BOOLEAN",
    isPublic: true,
    displayOrder: 10,
  },
  {
    channel: "KIOSK",
    group: "kiosk",
    key: "cartEnabled",
    label: "Enable Kiosk Cart",
    value: true,
    defaultValue: true,
    dataType: "BOOLEAN",
    isPublic: true,
    displayOrder: 20,
  },
  {
    channel: "KIOSK",
    group: "kiosk",
    key: "qrHandoffEnabled",
    label: "Enable QR Mobile Handoff",
    value: true,
    defaultValue: true,
    dataType: "BOOLEAN",
    isPublic: true,
    displayOrder: 30,
  },
  {
    channel: "KIOSK",
    group: "kiosk",
    key: "voiceInputEnabled",
    label: "Enable Voice Input",
    value: true,
    defaultValue: true,
    dataType: "BOOLEAN",
    isPublic: true,
    displayOrder: 40,
  },
  {
    channel: "KIOSK",
    group: "kiosk",
    key: "textToSpeechEnabled",
    label: "Enable Text to Speech",
    value: true,
    defaultValue: true,
    dataType: "BOOLEAN",
    isPublic: true,
    displayOrder: 50,
  },
  {
    channel: "KIOSK",
    group: "kiosk",
    key: "autoSessionResetEnabled",
    label: "Enable Automatic Session Reset",
    value: true,
    defaultValue: true,
    dataType: "BOOLEAN",
    isPublic: true,
    displayOrder: 60,
  },
  {
    channel: "KIOSK",
    group: "kiosk",
    key: "idleTimeoutSeconds",
    label: "Idle Timeout in Seconds",
    value: 120,
    defaultValue: 120,
    dataType: "NUMBER",
    isPublic: true,
    displayOrder: 70,
  },
  {
    channel: "KIOSK",
    group: "kiosk",
    key: "sessionResetSeconds",
    label: "Session Reset Delay",
    value: 15,
    defaultValue: 15,
    dataType: "NUMBER",
    isPublic: true,
    displayOrder: 80,
  },
  {
    channel: "KIOSK",
    group: "kiosk",
    key: "heartbeatIntervalSeconds",
    label: "Device Heartbeat Interval",
    value: 60,
    defaultValue: 60,
    dataType: "NUMBER",
    isPublic: true,
    displayOrder: 90,
  },
  {
    channel: "KIOSK",
    group: "kiosk",
    key: "orientation",
    label: "Kiosk Orientation",
    value: "PORTRAIT",
    defaultValue: "PORTRAIT",
    dataType: "SELECT",
    options: [
      {
        label: "Portrait",
        value: "PORTRAIT",
      },
      {
        label: "Landscape",
        value: "LANDSCAPE",
      },
    ],
    isPublic: true,
    displayOrder: 100,
  },

  // COMMERCE
  {
    channel: "GLOBAL",
    group: "commerce",
    key: "currency",
    label: "Default Currency",
    value: "AED",
    defaultValue: "AED",
    dataType: "SELECT",
    options: [
      {
        label: "UAE Dirham",
        value: "AED",
      },
      {
        label: "US Dollar",
        value: "USD",
      },
    ],
    isPublic: true,
    isRequired: true,
    displayOrder: 10,
  },
  {
    channel: "GLOBAL",
    group: "commerce",
    key: "timezone",
    label: "Business Time Zone",
    value: "Asia/Dubai",
    defaultValue: "Asia/Dubai",
    dataType: "SELECT",
    options: [
      {
        label: "Dubai",
        value: "Asia/Dubai",
      },
    ],
    isPublic: true,
    isRequired: true,
    displayOrder: 20,
  },
  {
    channel: "GLOBAL",
    group: "commerce",
    key: "taxInclusive",
    label: "Prices Include Tax",
    value: true,
    defaultValue: true,
    dataType: "BOOLEAN",
    isPublic: true,
    displayOrder: 30,
  },
  {
    channel: "GLOBAL",
    group: "commerce",
    key: "lowStockThreshold",
    label: "Default Low Stock Threshold",
    value: 5,
    defaultValue: 5,
    dataType: "NUMBER",
    isPublic: false,
    displayOrder: 40,
  },
  {
    channel: "GLOBAL",
    group: "commerce",
    key: "allowBackorders",
    label: "Allow Backorders",
    value: false,
    defaultValue: false,
    dataType: "BOOLEAN",
    isPublic: false,
    displayOrder: 50,
  },

  // CONTACT
  {
    channel: "GLOBAL",
    group: "contact",
    key: "supportEmail",
    label: "Support Email",
    value: "support@myshops.ae",
    defaultValue: "support@myshops.ae",
    dataType: "EMAIL",
    isPublic: true,
    displayOrder: 10,
  },
  {
    channel: "GLOBAL",
    group: "contact",
    key: "supportPhone",
    label: "Support Phone",
    value: "",
    defaultValue: "",
    dataType: "STRING",
    isPublic: true,
    displayOrder: 20,
  },
  {
    channel: "GLOBAL",
    group: "contact",
    key: "whatsAppNumber",
    label: "WhatsApp Number",
    value: "",
    defaultValue: "",
    dataType: "STRING",
    isPublic: true,
    displayOrder: 30,
  },
];

const run = async () => {
  try {
    await db.sequelize.authenticate();
    await db.sequelize.sync({
      alter: false,
    });

    const company =
      await db.Company.findOne({
        where: {
          code: "MYSHOPS",
          isActive: true,
        },
      });

    if (!company) {
      throw new Error(
        "MyShops company was not found. Run the initial administrator seed first."
      );
    }

    for (const item of settings) {
      await db.SystemSetting.findOrCreate({
        where: {
          companyId: company.id,
          channel: item.channel,
          group: item.group,
          key: item.key,
        },
        defaults: {
          companyId: company.id,
          ...item,
          isEditable: true,
          isRequired:
            item.isRequired || false,
          isActive: true,
        },
      });
    }

    console.log(
      "MyShops system settings seeded successfully."
    );
  } catch (error) {
    console.error(
      "System settings seed failed:"
    );
    console.error(error);
    process.exitCode = 1;
  } finally {
    await db.sequelize.close();
  }
};

run();