"use client";
import { Filter, Search, X } from "lucide-react";
import { useRouter, useSearchParams } from "next/navigation";
import { useState } from "react";
import BestsellerFilters,{type BestsellerFiltersData} from "./BestsellerFilters";
const sorts=[["FEATURED","Featured"],["PRICE_ASC","Price: Low to High"],["PRICE_DESC","Price: High to Low"],["NAME_ASC","Name: A to Z"],["NAME_DESC","Name: Z to A"]];
export default function BestsellerToolbar({totalItems,filters}:{totalItems:number;filters:BestsellerFiltersData}) {
 const router=useRouter(),sp=useSearchParams(),[open,setOpen]=useState(false);
 const update=(k:string,v:string)=>{const p=new URLSearchParams(sp.toString());v?p.set(k,v):p.delete(k);p.delete("page");const q=p.toString();router.push(q?`?${q}`:"?",{scroll:false})};
 const search=(fd:FormData)=>update("search",String(fd.get("search")||"").trim());
 return <><div className="mb-5 flex flex-col gap-3 rounded-2xl border border-storefront-border-light bg-storefront-surface p-3 sm:flex-row sm:items-center sm:justify-between"><p className="text-sm text-storefront-muted"><strong className="text-storefront-text">{totalItems}</strong> products found</p><div className="flex flex-col gap-2 sm:flex-row"><form action={search} className="relative sm:w-64"><Search size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-storefront-muted"/><input name="search" defaultValue={sp.get("search")||""} placeholder="Search bestsellers" className="h-11 w-full rounded-storefront-button border border-storefront-border-light bg-white pl-9 pr-3 text-sm"/></form><div className="flex gap-2"><button type="button" onClick={()=>setOpen(true)} className="inline-flex h-11 items-center gap-2 rounded-storefront-button border border-storefront-border-light bg-white px-4 text-sm font-bold lg:hidden"><Filter size={16}/>Filters</button><select value={sp.get("sort")||"FEATURED"} onChange={e=>update("sort",e.target.value)} className="h-11 flex-1 rounded-storefront-button border border-storefront-border-light bg-white px-3 text-sm sm:min-w-52">{sorts.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></div></div></div>{open?<div className="fixed inset-0 z-[100] lg:hidden"><button type="button" aria-label="Close filters" onClick={()=>setOpen(false)} className="absolute inset-0 bg-black/40"/><div className="absolute inset-y-0 right-0 w-[88%] max-w-sm overflow-y-auto bg-white p-5 shadow-2xl"><div className="mb-5 flex justify-between"><h2 className="text-lg font-black">Filters</h2><button type="button" onClick={()=>setOpen(false)}><X size={20}/></button></div><BestsellerFilters filters={filters} onApplied={()=>setOpen(false)}/></div></div>:null}</>;
}