"use client";
import { useRouter, useSearchParams } from "next/navigation";
export interface BestsellerFilterOption { id:string; label:string; count:number }
export interface BestsellerFiltersData { categories:BestsellerFilterOption[]; brands:BestsellerFilterOption[]; minimumPrice:number|null; maximumPrice:number|null; currencyCode:string }
const csv=(v:string|null)=>v?v.split(",").map(x=>x.trim()).filter(Boolean):[];
export default function BestsellerFilters({filters,onApplied}:{filters:BestsellerFiltersData;onApplied?:()=>void}) {
 const router=useRouter(),sp=useSearchParams();
 const go=(p:URLSearchParams)=>{p.delete("page");const q=p.toString();router.push(q?`?${q}`:"?",{scroll:false});onApplied?.()};
 const toggle=(key:"brandIds"|"categoryIds",id:string,checked:boolean)=>{const p=new URLSearchParams(sp.toString()),s=new Set(csv(p.get(key)));checked?s.add(id):s.delete(id);s.size?p.set(key,[...s].join(",")):p.delete(key);go(p)};
 const clear=()=>{const p=new URLSearchParams(sp.toString());["categoryIds","brandIds","minPrice","maxPrice","search","sort","page"].forEach(k=>p.delete(k));go(p)};
 const price=(fd:FormData)=>{const p=new URLSearchParams(sp.toString()),a=String(fd.get("minPrice")||"").trim(),b=String(fd.get("maxPrice")||"").trim();a?p.set("minPrice",a):p.delete("minPrice");b?p.set("maxPrice",b):p.delete("maxPrice");go(p)};
 const opts=(title:string,items:BestsellerFilterOption[],selected:Set<string>,key:"brandIds"|"categoryIds")=>items.length?<section className="border-t border-storefront-border-light pt-5"><h3 className="mb-3 text-sm font-black">{title}</h3><div className="max-h-64 space-y-2 overflow-auto pr-1">{items.map(o=><label key={o.id} className="flex cursor-pointer items-center justify-between gap-3 rounded-lg px-2 py-1.5 text-sm hover:bg-storefront-secondary"><span className="flex min-w-0 items-center gap-2"><input type="checkbox" checked={selected.has(o.id)} onChange={e=>toggle(key,o.id,e.target.checked)} className="h-4 w-4 accent-[var(--storefront-primary)]"/><span className="truncate">{o.label}</span></span><span className="text-xs text-storefront-muted">{o.count}</span></label>)}</div></section>:null;
 return <div className="space-y-6"><div className="flex items-center justify-between"><h2 className="text-lg font-black">Filters</h2><button type="button" onClick={clear} className="text-xs font-bold text-storefront-primary">Clear all</button></div>{opts("Categories",filters.categories,new Set(csv(sp.get("categoryIds"))),"categoryIds")}{opts("Brand",filters.brands,new Set(csv(sp.get("brandIds"))),"brandIds")}<section className="border-t border-storefront-border-light pt-5"><h3 className="mb-1 text-sm font-black">Price</h3><p className="mb-3 text-xs text-storefront-muted">{filters.currencyCode}</p><form action={price} className="space-y-3"><div className="grid grid-cols-2 gap-2"><input name="minPrice" type="number" min="0" step=".01" defaultValue={sp.get("minPrice")??filters.minimumPrice??""} placeholder="Min" className="h-10 min-w-0 rounded-lg border border-storefront-border-light px-3 text-sm"/><input name="maxPrice" type="number" min="0" step=".01" defaultValue={sp.get("maxPrice")??filters.maximumPrice??""} placeholder="Max" className="h-10 min-w-0 rounded-lg border border-storefront-border-light px-3 text-sm"/></div><button className="h-10 w-full rounded-storefront-button bg-storefront-primary text-xs font-bold text-white">Apply price</button></form></section></div>;
}